remote_theme: sujaykundu777/devlopr-jekyll # Don't touch ( required for this theme)

# Edit your preferences below
title: Naoki Ohashi
subtitle: WordPress Plugin Developer
description: >- # this means to ignore newlines until "baseurl:"
  naoki-is.me - the blog and portfolio by Naoki Ohashi

url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: Blog
    url: /blog
  - text: About Me
    url: /about
  - text: Contact Me
    url: /contact

# Edit these details

author_logo: profile.png
author: Naoki Ohashi
author_bio: Hi, I'm Naoki Ohashi. I love to Code and CLI. I'm developing Gutenberg custom block plugin recently.
author_email: "n.globe.us@gmail.com"
author_location: Japan
author_website_url: "https://naoki-is.me"

author_work_experiences:
  - company_name: Vektor
    company_logo: vektor.png
    company_url: https://www.vektor-inc.co.jp/
    designation: WordPress plugin developer
    description: Worked on VWS - WordPress Plugin and Theme Store, VK-Blocks - Gutenberg Custom Block Plugin.
    visibility: true
  - company_name: Shikumizukuri - Freelancer
    company_logo: shikimizukuri.png
    company_url:
    designation: Web Developer
    description: Developed various website.
    visibility: true

# author_education_details:
# - college_logo: mit.png
#   college_name: MIT
#   college_url: https://mit.org
#   college_degree: CS Engineer
#   description: Bachelor of Technology
#   visibility: false

author_project_details:
  # - project_thumbnail: gamershub.png
  #   project_title: Gamers Hub
  #   project_description: A Platform built for Gamers and Game Devs
  #   project_url: https://gamershub.in
  #   visibility: true
  # - project_thumbnail: programmingebooks.png
  #   project_title: Programming Ebooks
  #   project_description: A Platform to easily find and read programming books
  #   project_url: https://programmingebooks.com
  #   visibility: true

# social links
twitter_username: naogify
github_username: naogify
facebook_username: naogify
# linkedin_username: johndoe
# behance_username: johndoe
instagram_username: naogify
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments using disqus
disqus_shortname: sujay-kundu

# wakatime username
wakatime_username: sujaykundu777

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]
# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

